### PR TITLE
Add GitHub Actions test config

### PR DESCRIPTION
**Pull request by jonafato**
Run a GitHub Action to run the existing test suite any time commits are
pushed to the `master` branch or a pull request targets it. Also include
an initial test matrix lay groundwork for future additional Python
version support.

### CODE REVIEW

**Comment by jonafato** [comment]
@sw00 I think this config is valid (though it's possible I missed something). Is Actions enabled on this repo?

**Comment by sw00** [comment]
I'm new to this myself, but it looks like the `$default-branch` macro is only for actions' workflow templates.

See: https://stackoverflow.com/a/65723433/821032

**Comment by jonafato** [comment]
Interesting, I thought I'd seen that working elsewhere, but it seems not. Thanks for catching that. I'll get this into a working state and then mark it as Ready for Review.

**Comment by jonafato** [comment]
This config appears to work as intended on a PR to my own fork (https://github.com/jonafato/billwarrior/pull/2) but doesn't trigger anything if that PR is closed. I suspect there might be a change needed to the actions section of this repository's settings in order to fully enable it.

**Comment by sw00** [comment]
Hmm. Quite puzzling. It looks like all relevant options are enabled:

image
image

Based on the [GH docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), I should be seeing an option to "Approve and run" but it's not there:

image


It looks correct to me, so I'm going to merge and hope it runs in future PRs. Otherwise, will amend it directly in main branch.

**Pull request merged**
